packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25

  # Dev tooling
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.15
  typescript: ^5.7.3

  # Misc
  zod: ^3.25.76

  # AI
  ai: ^4.1.54
  "@ai-sdk/amazon-bedrock": ^1.0.6
  "@ai-sdk/anthropic": ^1.0.6
  "@ai-sdk/deepseek": ^0.1.0
  "@ai-sdk/google": ^1.1.20
  "@ai-sdk/groq": ^1.1.0
  "@ai-sdk/mistral": ^1.1.15
  "@ai-sdk/openai": ^1.2.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.67.1
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/tanstack-react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824

catalogs:
  react19:
    react: 19.0.1
    react-dom: 19.0.1
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
